# Generated by Django 5.0.2 on 2024-02-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default/not_found.png', upload_to='recipe_img/', verbose_name='Изображение рецепта'),
        ),
    ]
